server:
  port: 10032
  servlet:
    session:
      cookie:
        same-site: lax
        secure: false
        http-only: true
spring:
  application:
    name: knygnesys
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/knygnesys_db
    username: knygnesys_db
    password: knygnesys_pw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui